---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# MarshallsVenn

<!-- badges: start -->

<!-- badges: end -->

Hello, my name is Marcel Ferreira (*Marshall*). Welcome to the Venn diagram building tool!

The purpose of Marshall tools is to facilitate the construction of high-level graphics for users not familiar with programming languages.All tools are and will ALWAYS be free. The applications are currently in the testing phase, if you find any problems during use, please contact us via [marcel.ferreira\@unesp.br](mailto:marcel.ferreira@unesp.br).

### How to use

You can choose to upload a file with the CSV extension or manually place your datasets in the boxes. CSV files must contain up to 4 columns (one for each set), the first line will be used as set titles.While it is possible to create Venn diagrams for numerous data sets, diagrams above 4 sets lose visual efficiency. If you want to work with a larger number of sets, we recommend exploring other graphics options. (**Coming soon on"Marshall Tools"**).

### Acknowledgment

I am grateful to the São Paulo State Research Support Foundation ([FAPESP](https://fapesp.br/ "FAPESP")), for its financial assistance. Process number **2018/05731-7**. This app would not be possible without tidyverse, shiny, viridis and ggvenn packages.

### Where find me?

I am currently a PhD student at the Bioassays and Dynamics Laboratory at the Biosciences Institute of Botucatu under the supervision of dr. [Willian Zambuzzi](https://scholar.google.com.br/citations?user=bMhT1QsAAAAJ&hl=pt-BR). I'm on [Twitter](https://twitter.com/marceelrf "marceelrf twitter"), and [Instagram](https://www.instagram.com/marceelrf/) on personal \@marceelrf accounts. Please check out my Github.

See you!
